language: android

jdk:
  - oraclejdk8

env:
  global:
    - secure: "OVfIL3ggaGcDgJJhdWxYTCo3u38SNPNUNPsv6adHp5wW0Y2n1CF1zcAnZXhTkGEjoGvi0RuV8ZLG9jbmQdqxd17qBeBf2XPWKxyG1SUfegDVSy9OPF8BY11Fsp9I5RP1W3T/c32KTc7zvhtAivq9mbcrBYJZhDCKpZkdTNliFQ0="

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - if [ -n "$encrypted_49e3b92debd1_key" ]; then openssl aes-256-cbc -K $encrypted_49e3b92debd1_key -iv $encrypted_49e3b92debd1_iv -in secrets.enc -out secrets -d; fi
  - if [ -n "$encrypted_49e3b92debd1_key" ]; then tar xvf secrets >/dev/null; fi
  - if [ -z "$encrypted_49e3b92debd1_key" ]; then touch local.properties; fi

after_success:
  - if [ -n "$GITHUB_API_KEY" ]; then .buildscript/deploy_alpha.sh; fi

script:
  - ./gradlew check assembleDebug assembleDebugAndroidTest -Dorg.gradle.jvmargs="-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
  - tar xf google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
  - echo "y" | ./google-cloud-sdk/bin/gcloud components update beta
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file settings/firebase-test-lab.json >/dev/null
  - ./google-cloud-sdk/bin/gcloud beta test android run --async --type instrumentation --app ./app/build/output/apk/app-debug.apk --test ./app/build/output/apk/app-debug-androidTest.apk --device-ids Nexus5 --os-version-ids 22 --locales en --orientations portrait --project api-project-429371117063

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9870bec6049c7309e68
    on_success: change
    on_failure: always
