---
project_identifier: gdgx-frisbee

files:
  -
    source: '/app/src/main/res/values/strings.xml'
    translation: '/app/src/main/res/values-%android_code%/strings.xml'
    languages_mapping:
      android_code:
        ar: ar
        cs: cs
        de: de
        es-ES: es
        fr: fr
        hi: hi
        hu: hu
        hy-AM: hy-rAM
        it: it
        ja: ja
        ko: ko
        lt: lt
        nl: nl
        pl: pl
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        ru: ru
        sk: sk
        sr-SP: sr
        th: th
        tr: tr
        uk: uk
        zh-CN: zh-rCN
        zh-HK: zh-rHK
        zh-TW: zh-rTW
